import { Theme } from '../theme';

export const THEME: Theme = {
    'error': '#744040',
    'success': '#437440',
    'success_alt': '#4a8079',
    'background': '#4f4f4f',
    'foreground': '#ddd',
    'border': '#ddd',
    'navbar_hover': '#fff',
    'navbar_bg': '#2f2f2f',
    'navbar_fg': '#bbb',
    'navbar_focus_bg': '#4f4f4f',
    'navbar_focus_fg': '#fff',
    'link': '#c67fc6',
    'link_hover': 'mediumpurple',
    'minihead_bg': '#4f4f4f',
    'minihead_fg': '#ddd',
    'editor_bg': '#4f4f4f',
    'editor_fg': '#ddd',

    'selection_bg': '#2f2f2f',

    'alert_fg': '#d9edf7',
    'alert_bg': '#406b74',
    'alert_border': '#bce8f1',
    'btn_pri_fg': '#d9edf7',
    'btn_pri_bg': '#406b74',
    'btn_pri_border': '#bce8f1',
    'btn_dng_fg': '#f7d9d9',
    'btn_dng_bg': '#744040',
    'btn_dng_border': '#f1bcbc',
    'btn_suc_fg': '#d9f7dd',
    'btn_suc_bg': '#437440',
    'btn_suc_border': '#bcf1be',
    'btn_hover': 'mediumpurple',

    'cm_builtin': '#bbb',
    'cm_comment': '#c67fc6',
    'cm_atom': '#ddd',
    'cm_number': '#ddd',
    'cm_prop': '#ddd',
    'cm_keyword': '#fff',
    'cm_string': '#ddd',
    'cm_variable': 'inherit',
    'cm_variable_alt': 'inherit',
    'cm_def': 'inherit',
    'cm_bracket': 'inherit',
    'cm_tag': 'inherit',
    'cm_link': 'inherit',
    'cm_error': 'inherit',

    'qr_fg': '#4f4f4f',
    'qr_bg': '#ddd',
};
