import { Theme } from '../theme';

export const THEME: Theme = {
    'error': 'black',
    'success': 'black',
    'success_alt': 'black',
    'background': 'black',
    'foreground': '#ccc',
    'border': 'crimson',
    'navbar_hover': 'lightcoral',
    'navbar_bg': 'black',
    'navbar_fg': 'crimson',
    'navbar_focus_bg': 'crimson',
    'navbar_focus_fg': 'black',
    'link': 'lightcoral',
    'link_hover': 'crimson',
    'minihead_bg': 'black',
    'minihead_fg': 'crimson',
    'editor_bg': 'black',
    'editor_fg': 'crimson',

    'selection_bg': 'crimson',

    'alert_fg': 'deeppink',
    'alert_bg': 'black',
    'alert_border': 'crimson',
    'btn_pri_fg': '#ccc',
    'btn_pri_bg': 'black',
    'btn_pri_border': 'deeppink',
    'btn_dng_fg': 'crimson',
    'btn_dng_bg': 'black',
    'btn_dng_border': '#d43f3a',
    'btn_suc_fg': '#266726',
    'btn_suc_bg': 'black',
    'btn_suc_border': '#4cae4c',
    'btn_hover': 'lightcoral',

    'cm_builtin': '#ccc',
    'cm_comment': '#555',
    'cm_atom': 'deeppink',
    'cm_number': 'deeppink',
    'cm_prop': 'deeppink',
    'cm_keyword': 'crimson',
    'cm_string': 'deeppink',
    'cm_variable': 'inherit',
    'cm_variable_alt': 'inherit',
    'cm_def': 'inherit',
    'cm_bracket': 'inherit',
    'cm_tag': 'inherit',
    'cm_link': 'inherit',
    'cm_error': 'inherit',

    'qr_fg': 'black',
    'qr_bg': '#ccc',

    'icon_fg': '#fcc7c7',
    'icon_bg': 'crimson',
};
