import { Theme } from '../theme';

export const THEME: Theme = {
    'error': '#fbe9e9',
    'success': '#e7fbf8',
    'success_alt': '#e7fbe0',
    'background': '#fffdf3',
    'foreground': '#883747',
    'border': '#34271e',
    'navbar_hover': '#a94f58',
    'navbar_bg': '#ecd97a',
    'navbar_fg': '#7c5f19',
    'navbar_focus_bg': '#a69150',
    'navbar_focus_fg': '#fff',
    'link': '#72533f',
    'link_hover': '#a94f58',
    'minihead_bg': '#fffdf3',
    'minihead_fg': '#7c5f19',
    'editor_bg': '#fffdf3',
    'editor_fg': '#34271e',

    'selection_bg': '#a69150',

    'alert_fg': '#7c5f19',
    'alert_bg': '#ecd97a',
    'alert_border': '#34271e',
    'btn_pri_fg': '#7c5f19',
    'btn_pri_bg': '#ecd97a',
    'btn_pri_border': '#34271e',
    'btn_dng_fg': '#ff9fb5',
    'btn_dng_bg': '#333',
    'btn_dng_border': '#d43f3a',
    'btn_suc_fg': '#266726',
    'btn_suc_bg': '#a9e7a9',
    'btn_suc_border': '#387e38',
    'btn_hover': '#a94f58',

    'cm_builtin': '#34271e',
    'cm_comment': '#d3a548',
    'cm_atom': '#887c24',
    'cm_number': '#887c24',
    'cm_prop': 'inherit',
    'cm_keyword': '#82681e',
    'cm_string': '#887c24',
    'cm_variable': 'inherit',
    'cm_variable_alt': 'inherit',
    'cm_def': 'inherit',
    'cm_bracket': 'inherit',
    'cm_tag': 'inherit',
    'cm_link': 'inherit',
    'cm_error': 'inherit',
};
