import { Theme } from '../theme';

export const THEME: Theme = {
    'error': '#ffdcdc',
    'success': '#d2ffd2',
    'success_alt': '#dcffff',
    'background': '#fefdfd',
    'foreground': '#3d1404',
    'border': '#795a2e',
    'navbar_hover': '#7b362d',
    'navbar_bg': '#e0dde0',
    'navbar_fg': '#150f0a',
    'navbar_focus_bg': '#3d1404',
    'navbar_focus_fg': '#fff',
    'link': '#c07460',
    'link_hover': '#150f0a',
    'minihead_bg': '#fefdfd',
    'minihead_fg': '#150f0a',
    'editor_bg': '#fefdfd',
    'editor_fg': '#795a2e',

    'selection_bg': '#da8e6a',

    'alert_fg': '#150f0a',
    'alert_bg': '#fadbcd',
    'alert_border': '#795a2e',
    'btn_pri_fg': '#150f0a',
    'btn_pri_bg': '#fadbcd',
    'btn_pri_border': '#795a2e',
    'btn_dng_fg': '#ff9fb5',
    'btn_dng_bg': '#333',
    'btn_dng_border': '#d43f3a',
    'btn_suc_fg': '#266726',
    'btn_suc_bg': '#a9e7a9',
    'btn_suc_border': '#4cae4c',
    'btn_hover': '#23527c',

    'cm_builtin': '#795a2e',
    'cm_comment': '#c07460',
    'cm_atom': '#150f0a',
    'cm_number': '#150f0a',
    'cm_prop': 'inherit',
    'cm_keyword': '#3d1404',
    'cm_string': '#150f0a',
    'cm_variable': 'inherit',
    'cm_variable_alt': 'inherit',
    'cm_def': 'inherit',
    'cm_bracket': 'inherit',
    'cm_tag': 'inherit',
    'cm_link': 'inherit',
    'cm_error': 'inherit',

    'qr_bg': '#fefdfd',
    'qr_fg': '#903612',

    'icon_bg': '#3d1404',
    'icon_fg': '#d7b55f',
};
