import { Theme } from '../theme';

export const THEME: Theme = {
    'error': 'black',
    'success': 'black',
    'success_alt': 'black',
    'background': 'black',
    'foreground': '#ccc',
    'border': 'lime',
    'navbar_hover': 'lightgreen',
    'navbar_bg': 'black',
    'navbar_fg': 'lime',
    'navbar_focus_bg': 'lime',
    'navbar_focus_fg': 'black',
    'link': 'lightgreen',
    'link_hover': 'lime',
    'minihead_bg': 'black',
    'minihead_fg': 'lime',
    'editor_bg': 'black',
    'editor_fg': 'lime',
    'alert_fg': 'lime',
    'alert_bg': 'black',
    'alert_border': 'lime',
    'btn_pri_fg': '#ccc',
    'btn_pri_bg': 'black',
    'btn_pri_border': 'lime',
    'btn_dng_fg': 'lime',
    'btn_dng_bg': 'black',
    'btn_dng_border': '#d43f3a',
    'btn_suc_fg': '#266726',
    'btn_suc_bg': 'black',
    'btn_suc_border': '#4cae4c',
    'btn_hover': 'lightgreen',

    'cm_builtin': '#ccc',
    'cm_comment': '#555',
    'cm_atom': 'lime',
    'cm_number': 'lime',
    'cm_prop': 'lime',
    'cm_keyword': 'lime',
    'cm_string': 'lime',
    'cm_variable': 'inherit',
    'cm_variable_alt': 'inherit',
    'cm_def': 'inherit',
    'cm_bracket': 'inherit',
    'cm_tag': 'inherit',
    'cm_link': 'inherit',
    'cm_error': 'inherit',
};
