import { Theme } from '../theme';

export const THEME: Theme = {
    'error': '#ffdcdc',
    'success_alt': '#d2ffd2',
    'success': '#dcffff',
    'background': '#fff',
    'foreground': '#333',
    'border': '#2f2f2f',
    'navbar_hover': '#fff',
    'navbar_bg': '#2f2f2f',
    'navbar_fg': '#bbb',
    'navbar_focus_bg': '#4f4f4f',
    'navbar_focus_fg': '#fff',
    'link': '#337ab7',
    'link_hover': '#23527c',
    'minihead_bg': '#fff',
    'minihead_fg': '#333',
    'editor_bg': '#fff',
    'editor_fg': '#31708f',

    'selection_bg': '#23527c',

    'alert_fg': '#164',
    'alert_bg': '#bce8f1',
    'alert_border': '#2e6da4',
    'btn_pri_fg': '#fff',
    'btn_pri_bg': '#337ab7',
    'btn_pri_border': '#2f2f2f',
    'btn_dng_fg': '#fff',
    'btn_dng_bg': '#d9534f',
    'btn_dng_border': '#2f2f2f',
    'btn_suc_fg': '#fff',
    'btn_suc_bg': '#5cb85c',
    'btn_suc_border': '#2f2f2f',
    'btn_hover': '#23527c',

    'cm_builtin': '#708',
    'cm_comment': '#337ab7',
    'cm_atom': '#164',
    'cm_number': '#164',
    'cm_prop': 'inherit',
    'cm_keyword': '#337ab7',
    'cm_string': '#164',
    'cm_variable': 'inherit',
    'cm_variable_alt': 'inherit',
    'cm_def': 'inherit',
    'cm_bracket': 'inherit',
    'cm_tag': 'inherit',
    'cm_link': 'inherit',
    'cm_error': 'inherit',

    'qr_bg': '#fff',
    'qr_fg': '#333',

    'icon_fg': '#bbb',
    'icon_bg': '#2f2f2f',
};
